server:
  port: 87
spring:
  application:
    name: oauth-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.102:1521:orcl
    username: ctcenternew
    password: ctcenternew
  jpa:
      database: oracle
      format-sql: true
      show-sql: true
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.Oracle10gDialect
      properties:
        hibernate:
          default_schema: ctcenternew
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://service1:8081/eureka #service1
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org.springframework.security: DEBUG
    com.ectrip.oauth: DEBUG