spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbc_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html


mybatis-plus:
  #读取mapper的xml配置
  mapper-locations: classpath:**/*.xml

#Swagger-ui 密码配置
spring.security.basic.path: /swagger-ui.html
spring.security.basic.enabled: true
spring.security.user.name: admin
spring.security.user.password: 123456