spring:
  application:
    name: api-gateway


server:
  port: 80


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url: http://localhost/swagger-ui.html
zuul:
  routes:
    user:
      path: /user/**
    order:
      path: /order/**
#  ignored-patterns: /**/api-docs/** #忽略某些url，让其404

